### ISSUE TITLE
On LeetCode problem 458. Poor Pigs It's giving wrong answer

### ISSUE THREAD

**Issue by sceary-expert** [sceary-expert/all_codes_with_bug#2]
[Click here](https://leetcode.com/problems/poor-pigs/) to see the question.
![image](https://user-images.githubusercontent.com/84634405/183251850-6d19b899-9034-41f8-b37c-5e07b78640f3.png)

**Comment by hitcodemann** [comment]
hello sir, can u assign this issue  to me?
